# Generated by Django 5.1.5 on 2025-02-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0003_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
