# Generated by Django 5.1.5 on 2025-02-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0005_jobseeker_registration_delete_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_registration',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
