# Generated by Django 5.1.5 on 2025-02-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0007_jobseeker_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Type_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jobseeker_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
    ]
