# Generated by Django 5.1.5 on 2025-02-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0008_company_type_master_jobseeker_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='JobAi_App.company_type_master'),
        ),
    ]
