# Generated by Django 5.1.5 on 2025-02-12 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0010_company_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_jobs',
            name='company_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='JobAi_App.company'),
        ),
    ]
