# Generated by Django 5.1.5 on 2025-02-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0012_company_jobs_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_joblist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=20, null=True)),
                ('job_number', models.CharField(max_length=50)),
                ('job_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('dateofpublish', models.DateField(max_length=20, null=True)),
                ('Lastdate', models.DateField(max_length=20, null=True)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='JobAi_App.company')),
            ],
        ),
        migrations.DeleteModel(
            name='company_jobs',
        ),
    ]
