# Generated by Django 5.1.5 on 2025-02-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0013_company_joblist_delete_company_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_joblist',
            name='salary',
        ),
        migrations.AlterField(
            model_name='company_joblist',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
