# Generated by Django 5.1.5 on 2025-02-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0014_remove_company_joblist_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_joblist',
            name='job_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company_joblist',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
