# Generated by Django 5.1.5 on 2025-02-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0015_alter_company_joblist_job_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_joblist',
            old_name='company_id',
            new_name='company',
        ),
    ]
