# Generated by Django 5.1.5 on 2025-02-14 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0016_rename_company_id_company_joblist_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='JobAi_App.jobseeker_registration'),
        ),
    ]
