# Generated by Django 5.1.5 on 2025-02-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0017_jobseeker_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_registration',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
