# Generated by Django 5.1.5 on 2025-02-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0020_alter_jobseeker_resume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
