# Generated by Django 5.1.5 on 2025-02-18 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0021_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_joblist',
            name='job_title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='JobAi_App.job_title'),
        ),
    ]
