# Generated by Django 5.1.5 on 2025-02-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0022_alter_company_joblist_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
