# Generated by Django 5.1.5 on 2025-02-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0023_jobseeker_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
    ]
