# Generated by Django 5.1.5 on 2025-02-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0024_company_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='profile_img',
        ),
    ]
