# Generated by Django 5.1.5 on 2025-02-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0026_company_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_registration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
