# Generated by Django 5.1.5 on 2025-02-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0028_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job',
            new_name='company_joblist',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('jobseeker', 'company_joblist')},
        ),
    ]
