# Generated by Django 5.1.5 on 2025-03-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0029_rename_job_jobapplication_company_joblist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_joblist',
            name='percent_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker_profile',
            name='percentage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
