# Generated by Django 5.1.5 on 2025-03-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0030_company_joblist_percent_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_profile',
            name='passoutyear',
            field=models.TextField(blank=True, null=True),
        ),
    ]
