# Generated by Django 5.1.5 on 2025-03-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0031_jobseeker_profile_passoutyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker_profile',
            name='dob',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
