# Generated by Django 5.1.5 on 2025-03-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0032_alter_jobseeker_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker_profile',
            name='dob',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
