# Generated by Django 5.1.5 on 2025-03-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0033_alter_jobseeker_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='JobAi_App.company_joblist')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='JobAi_App.jobseeker_profile')),
            ],
        ),
    ]
