# Generated by Django 5.1.5 on 2025-03-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0034_jobnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeDetails',
        ),
    ]
