# Generated by Django 5.1.5 on 2025-03-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0035_delete_resumedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobnotification',
            old_name='jobseeker',
            new_name='jobseeker_profile',
        ),
    ]
