# Generated by Django 5.1.5 on 2025-03-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0037_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
