# Generated by Django 5.1.5 on 2025-03-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0039_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_joblist',
            name='job_number',
        ),
    ]
