# Generated by Django 5.1.5 on 2025-03-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0040_remove_company_joblist_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
