# Generated by Django 5.1.5 on 2025-03-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0041_jobapplication_ats_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_joblist',
            name='job_description',
            field=models.CharField(blank=True, max_length=12000, null=True),
        ),
    ]
