# Generated by Django 5.1.5 on 2025-03-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0042_alter_company_joblist_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_notifications', to='JobAi_App.company')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_notifications', to='JobAi_App.jobapplication')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_notifications', to='JobAi_App.jobseeker_profile')),
            ],
        ),
    ]
