# Generated by Django 5.1.5 on 2025-03-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAi_App', '0043_companynotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyNotification',
        ),
    ]
